//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addit.AK.WBD.AK_Suche.DocumentGeneration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Addit.AK.WBD.DocumentGeneration")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExeptionMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExeptionMsg {
            get {
                return this.ExeptionMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ExeptionMsgField, value) != true)) {
                    this.ExeptionMsgField = value;
                    this.RaisePropertyChanged("ExeptionMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMsg {
            get {
                return this.ResponseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMsgField, value) != true)) {
                    this.ResponseMsgField = value;
                    this.RaisePropertyChanged("ResponseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentGeneration.IDocumentGeneration")]
    public interface IDocumentGeneration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentGeneration/doPrint", ReplyAction="http://tempuri.org/IDocumentGeneration/doPrintResponse")]
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doPrint(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDocumentGeneration/doPrint", ReplyAction="http://tempuri.org/IDocumentGeneration/doPrintResponse")]
        System.IAsyncResult BegindoPrint(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl, System.AsyncCallback callback, object asyncState);
        
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoPrint(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentGeneration/doSimplePrint", ReplyAction="http://tempuri.org/IDocumentGeneration/doSimplePrintResponse")]
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doSimplePrint(string sessionToken, string printer, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDocumentGeneration/doSimplePrint", ReplyAction="http://tempuri.org/IDocumentGeneration/doSimplePrintResponse")]
        System.IAsyncResult BegindoSimplePrint(string sessionToken, string printer, string fileName, System.AsyncCallback callback, object asyncState);
        
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoSimplePrint(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentGeneration/doPrintWithValues", ReplyAction="http://tempuri.org/IDocumentGeneration/doPrintWithValuesResponse")]
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doPrintWithValues(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDocumentGeneration/doPrintWithValues", ReplyAction="http://tempuri.org/IDocumentGeneration/doPrintWithValuesResponse")]
        System.IAsyncResult BegindoPrintWithValues(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list, System.AsyncCallback callback, object asyncState);
        
        Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoPrintWithValues(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentGenerationChannel : Addit.AK.WBD.AK_Suche.DocumentGeneration.IDocumentGeneration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class doPrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public doPrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Addit.AK.WBD.AK_Suche.DocumentGeneration.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class doSimplePrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public doSimplePrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Addit.AK.WBD.AK_Suche.DocumentGeneration.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class doPrintWithValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public doPrintWithValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Addit.AK.WBD.AK_Suche.DocumentGeneration.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentGenerationClient : System.ServiceModel.ClientBase<Addit.AK.WBD.AK_Suche.DocumentGeneration.IDocumentGeneration>, Addit.AK.WBD.AK_Suche.DocumentGeneration.IDocumentGeneration {
        
        private BeginOperationDelegate onBegindoPrintDelegate;
        
        private EndOperationDelegate onEnddoPrintDelegate;
        
        private System.Threading.SendOrPostCallback ondoPrintCompletedDelegate;
        
        private BeginOperationDelegate onBegindoSimplePrintDelegate;
        
        private EndOperationDelegate onEnddoSimplePrintDelegate;
        
        private System.Threading.SendOrPostCallback ondoSimplePrintCompletedDelegate;
        
        private BeginOperationDelegate onBegindoPrintWithValuesDelegate;
        
        private EndOperationDelegate onEnddoPrintWithValuesDelegate;
        
        private System.Threading.SendOrPostCallback ondoPrintWithValuesCompletedDelegate;
        
        public DocumentGenerationClient() {
        }
        
        public DocumentGenerationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentGenerationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentGenerationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentGenerationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<doPrintCompletedEventArgs> doPrintCompleted;
        
        public event System.EventHandler<doSimplePrintCompletedEventArgs> doSimplePrintCompleted;
        
        public event System.EventHandler<doPrintWithValuesCompletedEventArgs> doPrintWithValuesCompleted;
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doPrint(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl) {
            return base.Channel.doPrint(sessionToken, user, template, printer, bereich, bezirk, status, ablehnung, sort, von, bis, ant_ikey, wbd_bdl);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindoPrint(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindoPrint(sessionToken, user, template, printer, bereich, bezirk, status, ablehnung, sort, von, bis, ant_ikey, wbd_bdl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoPrint(System.IAsyncResult result) {
            return base.Channel.EnddoPrint(result);
        }
        
        private System.IAsyncResult OnBegindoPrint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionToken = ((string)(inValues[0]));
            string user = ((string)(inValues[1]));
            string template = ((string)(inValues[2]));
            string printer = ((string)(inValues[3]));
            string bereich = ((string)(inValues[4]));
            string bezirk = ((string)(inValues[5]));
            string status = ((string)(inValues[6]));
            string ablehnung = ((string)(inValues[7]));
            string sort = ((string)(inValues[8]));
            string von = ((string)(inValues[9]));
            string bis = ((string)(inValues[10]));
            string ant_ikey = ((string)(inValues[11]));
            int wbd_bdl = ((int)(inValues[12]));
            return this.BegindoPrint(sessionToken, user, template, printer, bereich, bezirk, status, ablehnung, sort, von, bis, ant_ikey, wbd_bdl, callback, asyncState);
        }
        
        private object[] OnEnddoPrint(System.IAsyncResult result) {
            Addit.AK.WBD.AK_Suche.DocumentGeneration.Response retVal = this.EnddoPrint(result);
            return new object[] {
                    retVal};
        }
        
        private void OndoPrintCompleted(object state) {
            if ((this.doPrintCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.doPrintCompleted(this, new doPrintCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void doPrintAsync(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl) {
            this.doPrintAsync(sessionToken, user, template, printer, bereich, bezirk, status, ablehnung, sort, von, bis, ant_ikey, wbd_bdl, null);
        }
        
        public void doPrintAsync(string sessionToken, string user, string template, string printer, string bereich, string bezirk, string status, string ablehnung, string sort, string von, string bis, string ant_ikey, int wbd_bdl, object userState) {
            if ((this.onBegindoPrintDelegate == null)) {
                this.onBegindoPrintDelegate = new BeginOperationDelegate(this.OnBegindoPrint);
            }
            if ((this.onEnddoPrintDelegate == null)) {
                this.onEnddoPrintDelegate = new EndOperationDelegate(this.OnEnddoPrint);
            }
            if ((this.ondoPrintCompletedDelegate == null)) {
                this.ondoPrintCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndoPrintCompleted);
            }
            base.InvokeAsync(this.onBegindoPrintDelegate, new object[] {
                        sessionToken,
                        user,
                        template,
                        printer,
                        bereich,
                        bezirk,
                        status,
                        ablehnung,
                        sort,
                        von,
                        bis,
                        ant_ikey,
                        wbd_bdl}, this.onEnddoPrintDelegate, this.ondoPrintCompletedDelegate, userState);
        }
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doSimplePrint(string sessionToken, string printer, string fileName) {
            return base.Channel.doSimplePrint(sessionToken, printer, fileName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindoSimplePrint(string sessionToken, string printer, string fileName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindoSimplePrint(sessionToken, printer, fileName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoSimplePrint(System.IAsyncResult result) {
            return base.Channel.EnddoSimplePrint(result);
        }
        
        private System.IAsyncResult OnBegindoSimplePrint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionToken = ((string)(inValues[0]));
            string printer = ((string)(inValues[1]));
            string fileName = ((string)(inValues[2]));
            return this.BegindoSimplePrint(sessionToken, printer, fileName, callback, asyncState);
        }
        
        private object[] OnEnddoSimplePrint(System.IAsyncResult result) {
            Addit.AK.WBD.AK_Suche.DocumentGeneration.Response retVal = this.EnddoSimplePrint(result);
            return new object[] {
                    retVal};
        }
        
        private void OndoSimplePrintCompleted(object state) {
            if ((this.doSimplePrintCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.doSimplePrintCompleted(this, new doSimplePrintCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void doSimplePrintAsync(string sessionToken, string printer, string fileName) {
            this.doSimplePrintAsync(sessionToken, printer, fileName, null);
        }
        
        public void doSimplePrintAsync(string sessionToken, string printer, string fileName, object userState) {
            if ((this.onBegindoSimplePrintDelegate == null)) {
                this.onBegindoSimplePrintDelegate = new BeginOperationDelegate(this.OnBegindoSimplePrint);
            }
            if ((this.onEnddoSimplePrintDelegate == null)) {
                this.onEnddoSimplePrintDelegate = new EndOperationDelegate(this.OnEnddoSimplePrint);
            }
            if ((this.ondoSimplePrintCompletedDelegate == null)) {
                this.ondoSimplePrintCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndoSimplePrintCompleted);
            }
            base.InvokeAsync(this.onBegindoSimplePrintDelegate, new object[] {
                        sessionToken,
                        printer,
                        fileName}, this.onEnddoSimplePrintDelegate, this.ondoSimplePrintCompletedDelegate, userState);
        }
        
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response doPrintWithValues(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list) {
            return base.Channel.doPrintWithValues(sessionToken, printer, templateName, values, list);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindoPrintWithValues(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindoPrintWithValues(sessionToken, printer, templateName, values, list, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Addit.AK.WBD.AK_Suche.DocumentGeneration.Response EnddoPrintWithValues(System.IAsyncResult result) {
            return base.Channel.EnddoPrintWithValues(result);
        }
        
        private System.IAsyncResult OnBegindoPrintWithValues(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionToken = ((string)(inValues[0]));
            string printer = ((string)(inValues[1]));
            string templateName = ((string)(inValues[2]));
            System.Collections.Generic.Dictionary<string, string> values = ((System.Collections.Generic.Dictionary<string, string>)(inValues[3]));
            string[] list = ((string[])(inValues[4]));
            return this.BegindoPrintWithValues(sessionToken, printer, templateName, values, list, callback, asyncState);
        }
        
        private object[] OnEnddoPrintWithValues(System.IAsyncResult result) {
            Addit.AK.WBD.AK_Suche.DocumentGeneration.Response retVal = this.EnddoPrintWithValues(result);
            return new object[] {
                    retVal};
        }
        
        private void OndoPrintWithValuesCompleted(object state) {
            if ((this.doPrintWithValuesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.doPrintWithValuesCompleted(this, new doPrintWithValuesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void doPrintWithValuesAsync(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list) {
            this.doPrintWithValuesAsync(sessionToken, printer, templateName, values, list, null);
        }
        
        public void doPrintWithValuesAsync(string sessionToken, string printer, string templateName, System.Collections.Generic.Dictionary<string, string> values, string[] list, object userState) {
            if ((this.onBegindoPrintWithValuesDelegate == null)) {
                this.onBegindoPrintWithValuesDelegate = new BeginOperationDelegate(this.OnBegindoPrintWithValues);
            }
            if ((this.onEnddoPrintWithValuesDelegate == null)) {
                this.onEnddoPrintWithValuesDelegate = new EndOperationDelegate(this.OnEnddoPrintWithValues);
            }
            if ((this.ondoPrintWithValuesCompletedDelegate == null)) {
                this.ondoPrintWithValuesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndoPrintWithValuesCompleted);
            }
            base.InvokeAsync(this.onBegindoPrintWithValuesDelegate, new object[] {
                        sessionToken,
                        printer,
                        templateName,
                        values,
                        list}, this.onEnddoPrintWithValuesDelegate, this.ondoPrintWithValuesCompletedDelegate, userState);
        }
    }
}
